version: "3.2"

services:
    db:
        image: postgres:9.6
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: expense_tracker
        ports:
            - "5432:5432"
