# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='expenses.AppUser')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='uses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='uses',
            field=models.IntegerField(default=0),
        ),
    ]
